/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ApifyApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Articles": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AssemblePost": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Authors": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FacebookPageId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FacebookUserAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FacebookUserId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FauxiosOrchestrator": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GenerateArticleContent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateArticleImage": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateAvatar": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateBiblicalTruthImage": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateMillerRevolutionImage": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateTruthVsFoundingData": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateTruthVsVerse": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateTruthVsVerseData": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateVoiceover": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Images": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "NewsdataApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PineconeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostRevolutionReelToFacebook": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PostToSocials": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PostTruthReelToFacebook": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PostTruthToFacebook": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcessedImages": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RenderRevolutionReel": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RenderTruthReel": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RenderVideo": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RevolutionReelOrchestrator": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "RunwayApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TruthReelOrchestrator": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "TruthVersesOrchestrator": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "TwitterAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterAccessTokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterApiSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VideoAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VideoOrchestrator": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "site": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}