/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Articles": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Authors": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ClearArticlesFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HistoricalThemes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ImageProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Images": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "NewsdataApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ProblemStats": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProcessedImages": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RealProblems": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SeedConceptsFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SocialMediaPoster": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TwitterAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterAccessTokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwitterApiSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "site": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}